import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Navigation from '../components/navigation';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>API Bois Documentation</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Navigation />
				TEST NEXT
			</main>

			<footer>
				PIED
			</footer>
		</div>
	)
}

export default Home
